# Project information
site_name: 'Stein Documentation'
site_description: 'A linter for config files with a customizable rule set'
site_author: 'Masaki ISHIYAMA'
site_url: 'https://b4b4r07.github.io/stein/'

theme:
  name: 'material'
  palette:
    primary: 'blue grey'
    accent: 'blue grey'
  logo:
    icon: 'school'
  favicon: 'assets/images/favicon.png'
  # feature:
  #   tabs: true

markdown_extensions:
  - fontawesome_markdown
  - meta
  - codehilite
  - admonition
  - toc:
      permalink: "#"
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink:
      repo_url_shortener: true
      repo_url_shorthand: true
      social_url_shorthand: true
      user: b4b4r07
      repo: stein
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Customization
extra:
  social:
    - type: globe
      link: https://tellme.tokyo
    - type: github
      link: https://github.com/b4b4r07
    - type: twitter
      link: https://twitter.com/b4b4r07

extra_css:
    - "https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css"

# Repository
repo_name: b4b4r07/stein
repo_url: https://github.com/b4b4r07/stein
edit_uri: edit/master/docs

# Copyright
copyright: 'Copyright &copy; 2019 Masaki ISHIYAMA'

# Pages and navigation pane
nav:
  - Concepts:
    - Policy as Code: concepts/policy-as-code.md
    - Policy: concepts/policy.md
  - Configuration:
    - Introduction: configuration/_index.md
    - configuration/load.md
    - Policy:
      - Rules: configuration/policy/rules.md
      - Config: configuration/policy/config.md
      - Variables: configuration/policy/variables.md
      - Functions: configuration/policy/functions.md
    - Syntax:
      - Introduction: configuration/syntax/_index.md
      - Interpolation: configuration/syntax/interpolation.md
      - Built-in Funtions:
          - color: configuration/syntax/functions/color.md
          - exist: configuration/syntax/functions/exist.md
          - ext: configuration/syntax/functions/ext.md
          - glob: configuration/syntax/functions/glob.md
          - grep: configuration/syntax/functions/grep.md
          - jsonpath: configuration/syntax/functions/jsonpath.md
          - lookuplist: configuration/syntax/functions/lookuplist.md
          - match: configuration/syntax/functions/match.md
          - pathshorten: configuration/syntax/functions/pathshorten.md
          - wc: configuration/syntax/functions/wc.md
      - configuration/syntax/custom-functions.md
  - Getting Started:
    - intro/install.md
    - intro/rules.md
    - intro/run.md
  - Commands (CLI):
    - commands/_index.md
    - commands/apply.md
    - commands/fmt.md
