baseURL = "https://b4b4r07.github.io/stein/"
languageCode = "en-us"
title = "Stein Documentations"
theme = "hugo-theme-techdoc"

hasCJKLanguage = true
metaDataFormat = "yaml"

pygmentsUseClasses = true
pygmentsCodefences = true

[Params]
    # Souce Code repository section
    description = "A linter for config files with a customizable rule set"
    github_repository = "https://github.com/b4b4r07/stein"
    # version = "0.2.4"

    # Documentation repository section
    # documentation repository (set edit link to documentation repository)
    github_doc_repository = "https://github.com/b4b4r07/stein"

    # Analytic section
    google_analytics_id = "" # Your Google Analytics tracking id
    tag_manager_container_id = "" # Your Google Tag Manager container id
    google_site_verification = "" # Your Google Site Verification

    # Theme settings section
    dateformat = "" # default "2 Jan 2006"

    # path name excluded from documentation menu
    # menu_exclusion = []
    # menu_exclusion = ["archives", "blog", "entry", "post", "posts"]


# Global menu section
[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Issues"
    url = "https://github.com/b4b4r07/stein/issues/new"
    weight = 2

[[menu.main]]
    name = "Releases"
    url = "https://github.com/b4b4r07/stein/releases"
    weight = 3

[[menu.main]]
    name = "Changelog"
    url = "https://github.com/b4b4r07/stein/blob/master/CHANGELOG.md"
    weight = 4
